Regard.create(title: 'Hello World, CR')
Regard.create(title: 'Welcome to the react-rails app')
Regard.create(title: 'React on Rails')
Regard.create(title: 'Happy Reviewing dear CR')
Regard.create(title: 'Have a great week')
